"use client";
import{useState}from"react";import{useRouter}from"next/navigation";import{Trash2}from"lucide-react";
const columns=["backlog","ready","in-progress","review","blocked","done","cancelled"];
const colLabels:Record<string,string>={backlog:"Backlog",ready:"Ready","in-progress":"In Progress",review:"Review",blocked:"Blocked",done:"Done",cancelled:"Cancelled"};
const colColors:Record<string,string>={backlog:"border-slate-300 dark:border-slate-600",ready:"border-blue-300 dark:border-blue-600","in-progress":"border-amber-300 dark:border-amber-600",review:"border-purple-300 dark:border-purple-600",blocked:"border-red-300 dark:border-red-600",done:"border-green-300 dark:border-green-600",cancelled:"border-slate-300 dark:border-slate-600"};
const priorityColors:Record<string,string>={critical:"bg-red-500",high:"bg-amber-500",medium:"bg-blue-500",low:"bg-slate-400"};
export function KanbanBoard({items,projectId}:{items:any[];projectId:string}){const router=useRouter();const[confirmDelete,setConfirmDelete]=useState<string|null>(null);const[deleting,setDeleting]=useState(false);
async function move(itemId:string,newStatus:string){await fetch(`/api/projects/${projectId}/work-items/${itemId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:newStatus})});router.refresh()}
async function remove(itemId:string){setDeleting(true);await fetch(`/api/projects/${projectId}/work-items/${itemId}`,{method:"DELETE"});setDeleting(false);setConfirmDelete(null);router.refresh()}
return<div className="flex gap-4 overflow-x-auto pb-4 snap-x snap-mandatory" style={{scrollbarWidth:"thin"}}>{columns.map(col=>{const colItems=items.filter(i=>i.status===col);return<div key={col} className={`min-w-[260px] flex-1 snap-start rounded-2xl border-t-4 bg-white p-4 shadow-sm dark:bg-[#101b2d] ${colColors[col]}`}><h3 className="mb-3 text-sm font-semibold uppercase tracking-wider text-slate-500">{colLabels[col]} <span className="ml-1 rounded-full bg-slate-100 px-2 text-xs dark:bg-white/10">{colItems.length}</span></h3><div className="space-y-3">{colItems.map(i=><div key={i._id} className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:border-white/10 dark:bg-[#162438]"><div className="flex items-start justify-between gap-2"><h4 className="text-sm font-semibold">{i.title}</h4>{confirmDelete===i._id?<span className="flex gap-1 shrink-0"><button onClick={()=>setConfirmDelete(null)} className="text-xs px-2 py-1 rounded border">No</button><button onClick={()=>remove(i._id)} disabled={deleting} className="text-xs px-2 py-1 rounded bg-red-600 text-white disabled:opacity-60">Yes</button></span>:<button onClick={()=>setConfirmDelete(i._id)} className="shrink-0 text-slate-400 hover:text-red-500"><Trash2 className="h-3.5 w-3.5"/></button>}</div><div className="mt-2 flex flex-wrap items-center gap-2"><span className={`h-2 w-2 rounded-full ${priorityColors[i.priority]??"bg-slate-400"}`}/><span className="rounded bg-slate-100 px-1.5 py-0.5 text-[10px] dark:bg-white/10">{i.type}</span><span className="rounded bg-slate-100 px-1.5 py-0.5 text-[10px] dark:bg-white/10">{i.priority}</span></div><p className="mt-2 text-xs text-slate-500 line-clamp-2">{i.description||"No description"}</p><div className="mt-3"><select value={i.status} onChange={e=>move(i._id,e.target.value)} className="w-full rounded-lg border border-slate-200 bg-slate-50 px-2 py-1 text-xs dark:border-white/10 dark:bg-white/5"><option value="backlog">Backlog</option><option value="ready">Ready</option><option value="in-progress">In Progress</option><option value="review">Review</option><option value="blocked">Blocked</option><option value="done">Done</option><option value="cancelled">Cancelled</option></select></div></div>)}</div></div>})}</div>}
