"use client";
import { useEffect, useState } from "react";
import { Download, Share2, X } from "lucide-react";
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:"accepted"|"dismissed"}>};
const ios=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
const standalone=()=>matchMedia("(display-mode: standalone)").matches||(navigator as Navigator&{standalone?:boolean}).standalone===true;
export function PwaManager(){const[prompt,setPrompt]=useState<InstallPromptEvent|null>(null);const[iosHelp,setIosHelp]=useState(false);const[installed,setInstalled]=useState(false);
useEffect(()=>{setInstalled(standalone());if("serviceWorker"in navigator&&process.env.NODE_ENV==="production")navigator.serviceWorker.register("/sw.js",{scope:"/",updateViaCache:"none"}).catch(console.error);const before=(e:Event)=>{e.preventDefault();setPrompt(e as InstallPromptEvent)};const done=()=>{setInstalled(true);setPrompt(null);setIosHelp(false)};addEventListener("beforeinstallprompt",before);addEventListener("appinstalled",done);return()=>{removeEventListener("beforeinstallprompt",before);removeEventListener("appinstalled",done)}},[]);
async function install(){if(prompt){await prompt.prompt();const r=await prompt.userChoice;if(r.outcome==="accepted")setPrompt(null);return}if(ios())setIosHelp(true)}
if(installed)return null;return <>{(prompt||ios())&&<button type="button" onClick={install} className="fixed bottom-24 left-4 z-40 flex min-h-12 items-center gap-2 rounded-2xl bg-atlas-accent px-4 py-3 font-semibold text-slate-950 shadow-2xl lg:bottom-6 lg:left-auto lg:right-6" aria-label="Install Atlas Engineering OS"><Download className="h-5 w-5"/>Install Atlas</button>}{iosHelp&&<div className="fixed inset-0 z-50 flex items-end bg-black/70 p-3 sm:items-center sm:justify-center" role="dialog" aria-modal="true" aria-labelledby="ios-install-title"><section className="w-full max-w-md rounded-3xl bg-atlas-panel p-5"><div className="flex items-start justify-between gap-4"><div><h2 id="ios-install-title" className="text-xl font-semibold">Install Atlas</h2><p className="mt-2 text-slate-300">In Safari, select <strong>Share</strong>, then <strong>Add to Home Screen</strong>.</p></div><button type="button" onClick={()=>setIosHelp(false)} className="min-h-11 min-w-11 rounded-full bg-white/10 p-2" aria-label="Close"><X/></button></div><div className="mt-4 flex items-center gap-3 rounded-2xl bg-white/5 p-4"><Share2 className="text-atlas-accent"/><span>Share → Add to Home Screen</span></div></section></div>}</>}
