"use client";
import { useState } from "react";
import { Plus, X } from "lucide-react";
import { useRouter } from "next/navigation";

export function QuickCreate() {
  const [open,setOpen]=useState(false); const [type,setType]=useState("note"); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const router=useRouter();
  async function submit(e:React.FormEvent) { e.preventDefault(); if(!title.trim()) return; setSaving(true); setError(""); try { const res=await fetch("/api/quick-capture",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,title:title.trim(),description:description.trim()})}); if(!res.ok) throw new Error((await res.json()).error??"Save failed"); setTitle(""); setDescription(""); setOpen(false); router.refresh(); } catch(e){setError(e instanceof Error?e.message:"Save failed");} finally {setSaving(false);} }
  return <>{<button onClick={()=>setOpen(true)} className="fixed bottom-24 right-5 z-40 rounded-full bg-atlas-accent p-5 text-slate-950 shadow-2xl lg:bottom-8" aria-label="Quick create"><Plus className="h-6 w-6" /></button>}{open&&<div className="fixed inset-0 z-50 bg-black/60" role="dialog" aria-modal="true" aria-label="Quick capture"><form onSubmit={submit} className="absolute bottom-0 left-0 right-0 rounded-t-3xl bg-atlas-panel p-5 shadow-2xl lg:bottom-auto lg:left-auto lg:right-8 lg:top-24 lg:w-[420px] lg:rounded-3xl"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold">Quick Capture</h2><p className="text-sm text-slate-400">Save an update in seconds.</p></div><button type="button" onClick={()=>setOpen(false)} className="min-h-11 min-w-11 rounded-full bg-white/10 p-2" aria-label="Close"><X className="mx-auto h-5 w-5" /></button></div><label className="text-sm text-slate-400">Type<select value={type} onChange={e=>setType(e.target.value)} className="mt-1 min-h-12 w-full rounded-2xl border border-white/10 bg-atlas-bg px-4 py-3"><option value="note">Note</option><option value="task">Task</option><option value="bom">BOM Item</option><option value="research">Research</option><option value="experiment">Experiment</option></select></label><label className="mt-4 block text-sm text-slate-400">Title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} className="mt-1 min-h-12 w-full rounded-2xl border border-white/10 bg-atlas-bg px-4 py-3" /></label><label className="mt-4 block text-sm text-slate-400">Description<textarea maxLength={2000} value={description} onChange={e=>setDescription(e.target.value)} rows={4} className="mt-1 w-full rounded-2xl border border-white/10 bg-atlas-bg px-4 py-3" /></label>{error&&<p className="mt-3 text-sm text-atlas-red">{error}</p>}<button disabled={saving} className="mt-5 min-h-12 w-full rounded-2xl bg-atlas-accent px-4 py-3 font-bold text-slate-950 disabled:opacity-60">{saving?"Saving...":"Save Capture"}</button></form></div>}</>;
}
